In [56]:
import pandas as pd

season_data_21 = pd.read_csv('data/box_scores/season_box_ext_20202021.csv', converters={'GAME_ID': str})
season_data_20 = pd.read_csv(
    'data/box_scores/season_box_ext_20192020.csv', converters={'GAME_ID': str})
season_data_19 = pd.read_csv(
    'data/box_scores/season_box_ext_20182019.csv', converters={'GAME_ID': str})

# Concat all season data
season_all = pd.concat([season_data_21, season_data_20, season_data_19])

# Move GAME_ID to the front
season_all = season_all[["GAME_ID", "PTS_PAINT", "PTS_2ND_CHANCE", "PTS_FB", "LARGEST_LEAD", "LEAD_CHANGES", "TIMES_TIED", "TEAM_REBOUNDS", "PTS_OFF_TO", "PTS_QTR1",
                           "PTS_QTR2", "PTS_QTR3", "PTS_QTR4", "PTS_OT1", "PTS_OT2", "PTS_OT3", "PTS_OT4", "PTS_OT5", "PTS_OT6", "PTS_OT7", "PTS_OT8", "PTS_OT9", "PTS_OT10", "PTS", "W_PCT", "FG_PCT", "FG3_PCT", "FT_PCT", "OREB", "AST", "STL", "BLK", "TOV"]]

# Convert all columns to float expect GAME_ID
season_all = season_all.astype(
    {col: float for col in season_all.columns if col != 'GAME_ID'})

season_all = pd.concat([season_all, season_all.add_suffix('_1')], axis=1)

# # Create a list to store the combined rows
# combined_all = pd.DataFrame()
# # Iterate through the DataFrame, skipping every second row
# for i in range(0, len(season_all), 2):
#     tmp_df = pd.concat([season_all.iloc[i], season_all.iloc[i + 1]], axis=1)
#     combined_all = pd.concat([combined_all, tmp_df])

# Save to csv to data/training folder 
combined_all.to_csv('data/training/train_all.csv', index=False)

In [30]:
# Find comebacks
df_comeback = pd.DataFrame(columns=season_all.columns)
# Iterate over all rows pairwise based on GAME_ID
for i in range(0, len(season_all), 2):
    # Extract two rows at a time
    game_rows = season_all.iloc[i:i+2, :]

    # Get the row index of the max value in LARGEST_LEAD column
    # Largest Lead is not the winner
    if game_rows['LARGEST_LEAD'].idxmax() != game_rows['PTS'].idxmax():
        # if difference of largest lead column is larger then 10
        if game_rows['LARGEST_LEAD'].max() - game_rows['LARGEST_LEAD'].min() > 10:
            # Add the two rows to the comeback dataframe
            df_comeback = pd.concat([df_comeback, game_rows])

print(len(df_comeback))
df_comeback.head()

104

,GAME_ID,PTS_PAINT,PTS_2ND_CHANCE,PTS_FB,LARGEST_LEAD,LEAD_CHANGES,TIMES_TIED,TEAM_REBOUNDS,PTS_OFF_TO,PTS_QTR1,...,PTS,W_PCT,FG_PCT,FG3_PCT,FT_PCT,OREB,AST,STL,BLK,TOV
70,0022000950,56.0,27.0,8.0,4.0,9.0,10.0,12.0,17.0,16.0,...,143.0,0.531,0.467,0.474,0.750,17.0,31.0,7.0,7.0,13.0
71,0022000950,50.0,15.0,10.0,32.0,9.0,10.0,8.0,17.0,39.0,...,140.0,0.500,0.533,0.458,0.816,8.0,29.0,6.0,1.0,11.0
158,0022000543,62.0,15.0,9.0,19.0,15.0,8.0,6.0,36.0,28.0,...,111.0,0.389,0.518,0.393,0.933,11.0,29.0,8.0,1.0,25.0
159,0022000543,68.0,5.0,14.0,5.0,15.0,8.0,5.0,12.0,28.0,...,114.0,0.471,0.566,0.320,0.750,4.0,27.0,18.0,8.0,11.0
230,0022000614,56.0,19.0,14.0,17.0,2.0,2.0,6.0,19.0,34.0,...,124.0,0.425,0.523,0.485,0.800,10.0,38.0,8.0,3.0,16.0